name: IN5020

services:
  proxy:
    build: .
    environment:
      APP_ROLE: proxy
    ports:
      - "1099:1099"
    healthcheck:
      test: ["CMD", "java", "-cp", "/in5020/target/assignment1.jar", "com.group2.proxy.ProxyHealthCheck"]
      interval: 2s
      timeout: 2s
      retries: 15
      start_period: 2s
    

  server1:
    build: .
    environment:
      APP_ROLE: server
      SERVER_ZONE: 1
      SERVER_HOST: server1
    depends_on:
      proxy:
        condition: service_healthy

  server2:
    build: .
    environment:
      APP_ROLE: server
      SERVER_ZONE: 2
      SERVER_HOST: server2
    depends_on:
      proxy:
        condition: service_healthy

  server3:
    build: .
    environment:
      APP_ROLE: server
      SERVER_ZONE: 3
      SERVER_HOST: server3
    depends_on:
      proxy:
        condition: service_healthy

  server4:
    build: .
    environment:
      APP_ROLE: server
      SERVER_ZONE: 4
      SERVER_HOST: server4
    depends_on:
      proxy:
        condition: service_healthy

  server5:
    build: .
    environment:
      APP_ROLE: server
      SERVER_ZONE: 5
      SERVER_HOST: server5
    depends_on:
      proxy:
        condition: service_healthy


  client:
    build: .
    environment:
      APP_ROLE: client
      QUERY_FILE: /in5020/exercise_1_input.txt
    volumes:
      - ./exercise_1_input.txt:/in5020/exercise_1_input.txt:ro
    depends_on:
      proxy:
        condition: service_healthy
      server1:
        condition: service_started
      server2:
        condition: service_started
      server3:
        condition: service_started
      server4:
        condition: service_started
      server5:
        condition: service_started