name: IN5020

services:
  proxy:
    build: .
    environment:
      APP_ROLE: proxy
      VERBOSE: false
    ports:
      - "1099:1099"
    healthcheck:
      test: ["CMD", "java", "-cp", "/in5020/target/assignment1.jar", "com.group2.proxy.ProxyHealthCheck"]
      interval: 2s
      timeout: 2s
      retries: 15
      start_period: 2s
    

  serverA:
    build: .
    image: in5020-servera
    environment:
      APP_ROLE: server
      SERVER_HOST: serverA
      QUEUE_LOG_FILE: /in5020/output/serverA-queue.log
    volumes:
      - ./output:/in5020/output:rw
    depends_on:
      proxy:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "java", "-cp", "/in5020/target/assignment1.jar", "com.group2.server.ServerHealthCheck"]
      interval: 2s
      timeout: 2s
      retries: 15
      start_period: 2s

  serverB:
    build: .
    image: in5020-serverb
    environment:
      APP_ROLE: server
      SERVER_HOST: serverB
      QUEUE_LOG_FILE: /in5020/output/serverB-queue.log
    volumes:
      - ./output:/in5020/output:rw
    depends_on:
      proxy:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "java", "-cp", "/in5020/target/assignment1.jar", "com.group2.server.ServerHealthCheck"]
      interval: 2s
      timeout: 2s
      retries: 15
      start_period: 2s

  serverC:
    build: .
    image: in5020-serverc
    environment:
      APP_ROLE: server
      SERVER_HOST: serverC
      QUEUE_LOG_FILE: /in5020/output/serverC-queue.log
    volumes:
      - ./output:/in5020/output:rw
    depends_on:
      proxy:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "java", "-cp", "/in5020/target/assignment1.jar", "com.group2.server.ServerHealthCheck"]
      interval: 2s
      timeout: 2s
      retries: 15
      start_period: 2s

  serverD:
    build: .
    image: in5020-serverd
    environment:
      APP_ROLE: server
      SERVER_HOST: serverD
      QUEUE_LOG_FILE: /in5020/output/serverD-queue.log
    volumes:
      - ./output:/in5020/output:rw
    depends_on:
      proxy:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "java", "-cp", "/in5020/target/assignment1.jar", "com.group2.server.ServerHealthCheck"]
      interval: 2s
      timeout: 2s
      retries: 15
      start_period: 2s

  serverE:
    build: .
    image: in5020-servere
    environment:
      APP_ROLE: server
      SERVER_HOST: serverE
      QUEUE_LOG_FILE: /in5020/output/serverE-queue.log
    volumes:
      - ./output:/in5020/output:rw
    depends_on:
      proxy:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "java", "-cp", "/in5020/target/assignment1.jar", "com.group2.server.ServerHealthCheck"]
      interval: 2s
      timeout: 2s
      retries: 15
      start_period: 2s


  client:
    build: .
    environment:
      APP_ROLE: client
      QUERY_FILE: /in5020/exercise_1_input.txt
      OUTPUT_FILE: /in5020/output/client-output.txt
    volumes:
      - ./exercise_1_input.txt:/in5020/exercise_1_input.txt:ro
      - ./output:/in5020/output:rw
    depends_on:
      proxy:
        condition: service_healthy
      serverA:
        condition: service_healthy
      serverB:
        condition: service_healthy
      serverC:
        condition: service_healthy
      serverD:
        condition: service_healthy
      serverE:
        condition: service_healthy